[package]
name = "imtui"
version = "0.1.0"
authors = ["Shaheen Gandhi <shaheen@oculus.com>"]
description = "High-level Rust bindings for imtui"
categories = ["api-bindings"]
edition = "2018"
readme = "README.md"

[dependencies]

[workspace]
members = [
    "imtui-sys"
]

exclude = [
    "imtui-examples",
    "imtui-sys-bindgen",
    "imgui-rs"
]
