[package]
name = "imtui-sys-bindgen"
version = "0.1.0"
authors = ["Shaheen Gandhi <shaheen@oculus.com>"]
edition = "2018"
description = "imtui-sys bindings updater"
publish = false

[dependencies]
bindgen = "0.52"
failure = "0.1"

[profile.dev]
opt-level = 0
debug = true
