[package]
name = "imtui-examples"
version = "0.1.0"
authors = ["Shaheen Gandhi <shaheen@oculus.com>"]
edition = "2018"
description = "imtui crate examples"
publish = false

[dev-dependencies]
imtui = { version = "0.1.0", path = "../" }
imgui = { version = "0.2.1", path = "../imgui-rs" }
